test: no auto updater and disable agent postback

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -180,6 +180,64 @@ jobs:
           }
           Write-Output "All expected log lines found"
 
+      - name: Delete log file
+        shell: pwsh
+        run: |
+          Remove-Item -Force -ErrorAction SilentlyContinue "C:\ProgramData\RewstRemoteAgent\${{ vars.IT_ORG_ID }}\rewst_agent.log"
+
+      - name: Update agent
+        shell: pwsh
+        run: |
+          ./dist/rewst_agent_config.win.exe --update --org-id ${{ vars.IT_ORG_ID }} --no-auto-updates --disable-agent-postback
+
+      - name: Check logs for no auto updater
+        shell: pwsh
+        run: |
+          $logFile = "C:\ProgramData\RewstRemoteAgent\${{ vars.IT_ORG_ID }}\rewst_agent.log"
+          $logContent = Get-Content $logFile -Raw
+          Write-Output $logContent
+
+          if ($logContent -match [regex]::Escape("Starting auto updater")) {
+            Write-Error "Unexpected log line found: Starting auto updater"
+            exit 1
+          }
+          Write-Output "Confirmed: no 'Starting auto updater' log line found"
+
+      - name: Send test command
+        shell: pwsh
+        run: |
+          curl --location '${{ vars.IT_SEND_COMMAND_TRIGGER_URL }}' `
+          --form 'device_id="${{ steps.get_device_id.outputs.value }}"' `
+          --form 'commands="[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
+
+          $PS_Results = New-Object -TypeName psobject
+
+          # Start of typed powershell
+          $PS_Results | Add-Member -MemberType NoteProperty -Name \"error\" -Value \"\"
+          $PS_Results | Add-Member -MemberType NoteProperty -Name \"output\" -Value \"hello world`n\"
+
+          # Post results back to Rewst
+          $postData = $PS_Results | ConvertTo-Json
+          Invoke-RestMethod -Method \"Post\" -Uri $post_url -Body $postData -ContentType \"application/json\""'
+
+      - name: Check logs for command received
+        shell: pwsh
+        run: |
+          $logFile = "C:\ProgramData\RewstRemoteAgent\${{ vars.IT_ORG_ID }}\rewst_agent.log"
+          $logContent = Get-Content $logFile -Raw
+          Write-Output $logContent
+
+          if ($logContent -notmatch [regex]::Escape("Command completed")) {
+            Write-Error "Expected log line not found: Command completed"
+            exit 1
+          }
+
+          if ($logContent -match [regex]::Escape("Postback already sent")) {
+            Write-Error "Unexpected log line found: Postback already sent"
+            exit 1
+          }
+          Write-Output "All log checks passed"
+
       - name: Uninstall agent
         shell: pwsh
         run: |
